# LunaChat v1.0.0
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013

displayJapanize: false
noJoinAsGlobal: false
loggingChat: true
globalMarker: '!'
autoLeavingOnMove: false
autoLeavingOnQuit: false
zeroMemberRemove: false
