# LunaChat v2.2.0
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2013

noJoinAsGlobal: true
loggingChat: true
displayChatOnConsole: false
globalMarker: '!'
zeroMemberRemove: false
showListOnJoin: false
createChannelOnJoinCommand: true
globalChannel: ''
sendBroadcastChannelChatToDynmap: true

ngword: []
ngwordAction: mask

japanizeType: GoogleIME
japanizeDisplayLine: 1
japanizeLine1Format: '%msg &7(%japanize)'
japanizeLine2Format: '&6[JP] %japanize'
noneJapanizeMarker: '#'
