# LunaChat v1.5.0
# @author     ucchy
# @license    GPLv3
# @copyright  Copyright ucchy 2013

displayJapanize: true
noJoinAsGlobal: true
loggingChat: true
globalMarker: '!'
zeroMemberRemove: false
showListOnJoin: false
createChannelOnJoinCommand: true
globalChannel: ''
ngword: []
ngwordAction: mask
