# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2013


# -------------------- チャンネルチャット設定 --------------------

# チャンネルチャット機能を利用可能にするかどうか
# Japanize機能のみを利用したい場合は、falseにしてください。
enableChannelChat: true

# チャンネルチャットに入っていない人の発言を、グローバルとして扱うかどうか
noJoinAsGlobal: true

# チャンネルチャットの発言内容を、ログに残すかどうか
loggingChat: true

# チャンネルチャットの発言内容を、サーバーコンソールに表示するかどうか
displayChatOnConsole: false

# グローバルマーカー。
# これが発言の頭に入っている場合は、一時的にグローバル発言になる。
globalMarker: '!'

# 全てのメンバーが退出したときに、チャンネルを削除するかどうか
zeroMemberRemove: false

# ログイン時に、参加中チャンネルを表示するかどうか
showListOnJoin: false

# /ch join コマンドで存在しないチャンネルを指定したときに、チャンネルを新規作成して入室するかどうか
createChannelOnJoinCommand: true

# 通常のチャットの代わりに、既定として使用するグローバルチャンネル。
# グローバルチャンネルを作らず通常のチャットを使用する場合は、から文字列 「''」 を指定すること。
globalChannel: ''

# サーバーに参加したユーザーに必ず参加させるチャンネル。
# グローバルチャンネルとは別で指定できる。
# 複数のチャンネルを設定可能。例）forceJoinChannels: ['L', 'M', 'N']
forceJoinChannels: []

# formatコマンド実行時に、必ず含まれる必要があるキーワード。
formatConstraint: ['%username', '%msg']



# -------------------- dynmap連携設定 --------------------

# ブロードキャストチャンネルの発言内容を、dynmapに送信するかどうか。
# dynmapがロードされていない場合は、この設定は無視される（false扱い）。
sendBroadcastChannelChatToDynmap: true

# dynmapへ送信するときに、チャンネルのフォーマットを反映して送信するかどうか。
# trueにするとチャンネルフォーマットを反映したメッセージをdynmapに表示します。
# falseにするとメッセージのみをdynmapに表示します。
# 参考：https://github.com/ucchyocean/LunaChat/issues/68
sendFormattedMessageToDynmap: false

# dynmapのWebUIから発言された発言内容を表示するチャンネル。
# dynmapChannelが無指定で、globalChannelが指定されているなら、グローバルチャンネルに、
# dynmapChannelが無指定で、globalChannelも無指定なら、通常チャットに発言される。
dynmapChannel: ''



# -------------------- NGワード設定 --------------------

# NGワード設定。
# ここに設定されたワードを発言したプレイヤーは、NGワード部分がマスクされる。
ngword: []

# NGワード発言時の動作設定。mask、mute、kick、ban の4つのいずれかが設定可能。
# mask : NGワードをマスクする
# mute : NGワードをマスクしたのち、発言したプレイヤーをチャンネルからMuteする
# kick : NGワードをマスクしたのち、発言したプレイヤーをチャンネルからキックする
# ban  : NGワードをマスクしたのち、発言したプレイヤーをチャンネルからBANする
ngwordAction: mask



# -------------------- チャット装飾設定 --------------------
# チャンネルチャット機能を利用しないユーザーのための設定です。

# 通常チャット（非チャンネルチャット）の装飾を、LunaChatから行うかどうか
# Vault がロードされていない場合は、この設定は無視される（false扱い）。
enableNormalChatMessageFormat: true

# チャット装飾のフォーマット設定です。
normalChatMessageFormat: '%prefix&f<%username>%suffix&f %msg'



# -------------------- Japanize変換設定 --------------------

# ローマ字をかな文字や漢字に変換する設定。
# none/kana/GoogleIME/SocialIME の4つのいずれかが設定可能。
# none      : 変換なし。
# kana      : かな変換のみ。
# GoogleIME : かな変換したのち、GoogleIMEを使ってIME変換する。(少し発言が重くなります。)
# SocialIME : かな変換したのち、SocialIMEを使ってIME変換する。(少し発言が重くなります。)
japanizeType: GoogleIME

# かな変換や漢字変換時に、
# 変換結果を元の発言内容と合わせて1行で表示するか、
# 変換結果のみを2行目に表示するかを、設定する。
japanizeDisplayLine: 1

# japanizeDisplayLine が 1 のときの、表示フォーマットを設定する。
japanizeLine1Format: '%msg &7(%japanize)'

# japanizeDisplayLine が 2 のときの、2行目の表示フォーマットを設定する。
japanizeLine2Format: '&6[JP] %japanize'

# 発言に含まれているプレイヤー名を、Japanize変換から除外するかどうかを設定する。
japanizeIgnorePlayerName: true

# ノンジャパナイズマーカー。
# これが発言の頭に入っている場合は、一時的にjapanizeを実行しない
noneJapanizeMarker: '#'
