name: LunaChat
main: com.github.ucchyocean.lc.LunaChat
version: 2.5.3
author: ucchy
description: チャンネルチャットプラグイン
softdepend: [Vault, dynmap]
commands:
  lunachat:
    description: lunachatのユーザーコマンド
    aliases: [ch, lc]
    usage: |
           /<command> join (channel) - チャンネルに参加します。
           /<command> leave - 参加しているチャンネルから退出します。
           /<command> list - チャンネルのリストを表示します。
           /<command> invite (name) - 指定した人をチャンネルチャットに招待します。
           /<command> accept - 招待を受けてチャンネルチャットに入室します。
           /<command> deny - 招待を拒否します。
           /<command> kick (name) - 指定した人をチャンネルチャットからキックします。
           /<command> ban (name) - 指定した人をチャンネルチャットからBANします。
           /<command> pardon (name) - 指定した人のBANを解除します。
           /<command> mute (name) - 指定した人をチャンネルチャットからMuteします。
           /<command> unmute (name) - 指定した人のMuteを解除します。
           /<command> hide [channel] - 指定したチャンネルの発言内容を非表示にします。指定を省略すると、現在自分が居るチャンネルが非表示になります。
           /<command> unhide [channel] - 指定したチャンネルの発言内容を非表示から表示に戻します。
           /<command> info [channel] - チャンネルの情報を表示します。
           /<command> create (channel) - チャンネルを作成します。
           /<command> remove [channel] - チャンネルを削除します。
           /<command> format [channel] (format...) - チャンネルのメッセージフォーマットを設定します。
           /<command> moderator [channel] (player...) - チャンネルのモデレーターを指定したプレイヤーに設定します。
           /<command> option (key=value...) - チャンネルのオプションを設定します。
           /<command> template (number) (template...) - メッセージフォーマットのテンプレートを登録します。
           /<command> reload - config.ymlの再読み込みをします。
           /<command> help [user|mod|admin] [page] - ヘルプを表示します。
  message:
    description: 1:1チャット送信コマンド
    aliases: [msg, tell, m, t]
    usage: /<command> (name) [message] - 指定した人との1:1チャットを開始します。
    permission: lunachat.message
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  reply:
    description: 1:1チャット返信コマンド
    aliases: [r]
    usage: /<command> [message] - 受信した1:1チャットに返信します。
    permission: lunachat.reply
    permission-message: パーミッション "<permission>" が無いため、実行できません。
  lcjapanize:
    description: lunachatのjapanizeオンオフ設定コマンド
    aliases: [japanize, jp]
    usage: |
           /<command> on|off - Turn on/off the Japanize conversion of your chat.
           /<command> (player) (on|off) - Turn on/off the Japanize conversion of other player's chat.
    permission: lunachat.japanize
    permission-message: You don't have the permission "<permission>".
permissions:
  lunachat.join:
    description: joinコマンドの使用権限
    default: true
  lunachat.leave:
    description: leaveコマンドの使用権限
    default: true
  lunachat.list:
    description: listコマンドの使用権限
    default: true
  lunachat.invite:
    description: inviteコマンドの使用権限
    default: true
  lunachat.accept:
    description: acceptコマンドの使用権限
    default: true
  lunachat.deny:
    description: denyコマンドの使用権限
    default: true
  lunachat.kick:
    description: kickコマンドの使用権限
    default: true
  lunachat.ban:
    description: banコマンドの使用権限
    default: true
  lunachat.pardon:
    description: pardonコマンドの使用権限
    default: true
  lunachat.mute:
    description: muteコマンドの使用権限
    default: true
  lunachat.unmute:
    description: unmuteコマンドの使用権限
    default: true
  lunachat.hide:
    description: hideコマンドの使用権限
    default: true
  lunachat.unhide:
    description: unhideコマンドの使用権限
    default: true
  lunachat.info:
    description: infoコマンドの使用権限
    default: true
  lunachat.create:
    description: createコマンドの使用権限
    default: true
  lunachat.remove:
    description: removeコマンドの使用権限
    default: true
  lunachat.format:
    description: formatコマンドの使用権限
    default: true
  lunachat.moderator:
    description: moderatorコマンドの使用権限
    default: true
  lunachat.option:
    description: optionコマンドの使用権限
    default: true
  lunachat.message:
    description: messageコマンドの使用権限
    default: true
  lunachat.reply:
    description: replyコマンドの使用権限
    default: true
  lunachat.help:
    description: helpコマンドの使用権限
    default: true
  lunachat.japanize:
    description: lunachatのjapanizeオンオフ設定コマンドの使用権限
    default: true
  lunachat.*:
    children:
      lunachat.join: true
      lunachat.leave: true
      lunachat.list: true
      lunachat.invite: true
      lunachat.accept: true
      lunachat.deny: true
      lunachat.kick: true
      lunachat.ban: true
      lunachat.pardon: true
      lunachat.mute: true
      lunachat.unmute: true
      lunachat.hide: true
      lunachat.unhide: true
      lunachat.info: true
      lunachat.create: true
      lunachat.remove: true
      lunachat.format: true
      lunachat.moderator: true
      lunachat.option: true
      lunachat.message: true
      lunachat.reply: true
      lunachat.help: true
      lunachat.japanize: true
    description: 一般ユーザー向けの全コマンドの使用権限
  lunachat-admin.template:
    description: templateコマンドの使用権限
    default: op
  lunachat-admin.reload:
    description: reloadコマンドの使用権限
    default: op
  lunachat-admin.japanize-other:
    description: 他者のjapanizeオンオフ設定コマンドの使用権限
    default: op
  lunachat-admin.*:
    children:
      lunachat-admin.template: true
      lunachat-admin.reload: true
      lunachat-admin.japanize-other: true
    description: 管理者向けの全コマンドの使用権限
    